### PR TITLE
November Commits Review

### PR DESCRIPTION
**Pull request by MagestryMark**
Some typos were found as I reviewed all of the GitHub commits that were made since my last edit.

### CODE REVIEW

**Comment by Hobbes74** [comment]
I've marked it as ready for review by mistake.

**Comment by MagestryMark** [comment]
Not a problem.  Was it intentional that the Marauder's Lance Command Module went back to a 10% damage reduction for the whole lance?  I noticed that upgrades/base/Gear_General_Lance_Command_Module.json changes were reverted in the 8.8.6 commit list.

**Comment by MagestryMark** [comment]
Ah, never mind - I was looking at an old version.  I see that it's correct in Master

**Comment by MagestryMark** [comment]
Actually, this needs to go back into a Draft request.  It looks like I branched from the wrong spot, so incorporating my edits might undo later revisions.  I'll look into it more tomorrow

**Comment by MagestryMark** [comment]
Closed

**Pull request closed without merging**
